/* -------------------------------------------------------------------
   Code generated by SAS Task

   Generated on: Monday, March 8, 2021 at 12:00:47 AM
   By task: Linear Regression (2)

   Input Data: Local:COVID.COVID_NBH_SUMMARY
   Server:  Local
   ------------------------------------------------------------------- */
ods excel file="\\nappgsd01\domesticbanking\Retail Lending\Credit Cards - Common\Business Analytics\BI Team\Credit Card Reporting\Projects\ADH0820\Charts\SAS_Model.xlsx" ;
ods excel options(autofilter="1-5" sheet_name = "STEPWISE"
embedded_titles='yes' sheet_interval = 'none');

ods excel options(sheet_interval = 'proc' sheet_name = "VARIABLE PLOT");
ods graphics on;


ODS GRAPHICS ON;

%_eg_conditional_dropds(WORK.PREDLinRegPredictions,
		WORK.SORTTempTableSorted,
		WORK.TMP1TempTableForPlots);
/* -------------------------------------------------------------------
   Determine the data set's type attribute (if one is defined)
   and prepare it for addition to the data set/view which is
   generated in the following step.
   ------------------------------------------------------------------- */
DATA _NULL_;
	dsid = OPEN("COVID.COVID_NBH_SUMMARY", "I");
	dstype = ATTRC(DSID, "TYPE");
	IF TRIM(dstype) = " " THEN
		DO;
		CALL SYMPUT("_EG_DSTYPE_", "");
		CALL SYMPUT("_DSTYPE_VARS_", "");
		END;
	ELSE
		DO;
		CALL SYMPUT("_EG_DSTYPE_", "(TYPE=""" || TRIM(dstype) || """)");
		IF VARNUM(dsid, "_NAME_") NE 0 AND VARNUM(dsid, "_TYPE_") NE 0 THEN
			CALL SYMPUT("_DSTYPE_VARS_", "_TYPE_ _NAME_");
		ELSE IF VARNUM(dsid, "_TYPE_") NE 0 THEN
			CALL SYMPUT("_DSTYPE_VARS_", "_TYPE_");
		ELSE IF VARNUM(dsid, "_NAME_") NE 0 THEN
			CALL SYMPUT("_DSTYPE_VARS_", "_NAME_");
		ELSE
			CALL SYMPUT("_DSTYPE_VARS_", "");
		END;
	rc = CLOSE(dsid);
	STOP;
RUN;

/* -------------------------------------------------------------------
   Data set COVID.COVID_NBH_SUMMARY does not need to be sorted.
   ------------------------------------------------------------------- */
DATA WORK.SORTTempTableSorted &_EG_DSTYPE_ / VIEW=WORK.SORTTempTableSorted;
	SET COVID.COVID_NBH_SUMMARY;
RUN;
TITLE;
TITLE1 "Linear Regression Results";
FOOTNOTE;
FOOTNOTE1 "Generated by the SAS System (&_SASSERVERNAME, &SYSSCPL) on %TRIM(%QSYSFUNC(DATE(), NLDATE20.)) at %TRIM(%SYSFUNC(TIME(), TIMEAMPM12.))";
PROC REG DATA=WORK.SORTTempTableSorted
		PLOTS(ONLY)=ALL
	;
	Linear_Regression_Model: MODEL INFECTION_RATE = P_AGE_40_to_64 P_VM_Yes P_EDU_HS_Lower P_HH_5_Persons P_OCC_Ess_Yes P_IMM_Yes
		/		SELECTION=STEPWISE
		SLE=0.15
		SLS=0.15
		INCLUDE=0
		STB SS1 CORRB
	;

	OUTPUT OUT=WORK.PREDLinRegPredictions(LABEL="Linear regression predictions and statistics for COVID.COVID_NBH_SUMMARY")
		PREDICTED=predicted_INFECTION_RATE 
		RESIDUAL=residual_INFECTION_RATE 
		STUDENT=student_INFECTION_RATE 
		RSTUDENT=rstudent_INFECTION_RATE 
		LCL=lcl_INFECTION_RATE 
		LCLM=lclm_INFECTION_RATE 
		UCL=ucl_INFECTION_RATE 
		UCLM=uclm_INFECTION_RATE ;
RUN;
QUIT;

/* -------------------------------------------------------------------
   End of task code
   ------------------------------------------------------------------- */
RUN; QUIT;
%_eg_conditional_dropds(WORK.SORTTempTableSorted,
		WORK.TMP1TempTableForPlots);
TITLE; FOOTNOTE;
ODS GRAPHICS OFF;
